CREATE SEQUENCE PESSOA_ID;

CREATE TABLE PESSOA (
    ID     INTEGER NOT NULL,
    NOME   VARCHAR(80),
    SEXO   INTEGER,
    EMAIL  VARCHAR(100)
);

ALTER TABLE PESSOA ADD CONSTRAINT PK_PESSOA PRIMARY KEY (ID);

CREATE OR ALTER TRIGGER PESSOA_BI FOR PESSOA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(pessoa_id,1);
end;

CREATE SEQUENCE ENDERECO_ID;

CREATE TABLE ENDERECO (
    ID           INTEGER NOT NULL,
    LOGRADOURO   VARCHAR(80),
    NUMERO       VARCHAR(60),
    COMPLEMENTO  VARCHAR(80),
    BAIRRO       VARCHAR(60),
    CIDADE       VARCHAR(60),
    UF           VARCHAR(2),
    ID_PESSOA    INTEGER
);

ALTER TABLE ENDERECO ADD CONSTRAINT PK_ENDERECO PRIMARY KEY (ID);
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE OR ALTER TRIGGER ENDERECO_BI FOR ENDERECO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(endereco_id,1);
end;