CREATE TABLE PESSOA (
    ID      NUMERIC(18,0) NOT NULL,
    DTNASC  DATE,
    EMAIL   VARCHAR(255),
    GENERO  INTEGER,
    NOME    VARCHAR(255)
);

CREATE SEQUENCE PESSOA_ID;

ALTER TABLE PESSOA ADD PRIMARY KEY (ID);

CREATE OR ALTER TRIGGER PESSOA_BI FOR PESSOA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF ((NEW.ID < 0) OR (NEW.ID IS NULL)) THEN
    NEW.ID = GEN_ID(PESSOA_ID,1);
END